language: node_js
node_js:
        - "9"
        - "8"
        - "7"
        - "6"
        - "5"
        - "4"
script: echo "Running tests against $(node -v)..."
script: npm run install
script: npm run build
script: npm run test:unit
script: npm run test:e2e
