language: node_js
node_js:
        - "9"
        - "8"
        - "7"
        - "6"
addons:
        firefox: latest
before_script:
        - "export DISPLAY=:99.0"
        - "sh -e /etc/init.d/xvfb start"
script: npm run build-and-test
deploy:
        skip_cleanup: true
        provider: npm
        email: "fredrikaxk@gmail.com"
        api_key: $NPM_API_KEY
        on:
                node: "7"
                branch: master
